a$ git add .
$ git commit -m “add Dockerfile”
[master 5a0955f] add Dockerfile
 2 files changed, 22 insertions(+)
 create mode 100644 Dockerfile
 create mode 100644 index.html
$ git push 
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 611 bytes | 611.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
To github.com:PharosProduction/tutorial-docker-automated-builds.git
 13cb2bd..5a0955f master -> master